name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
      #- name: Lint
      #run: npm run lint
      - name: Run Tests
        uses: Borales/actions-yarn@v4.2.0
        with: 
          cmd: yarn ember test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Run Tests
        uses: Borales/actions-yarn@v4.2.0
        with: 
          cmd: yarn ember test
